title: BookManager
email: rain2473@naver.com
description: >- # this means to ignore newlines until "baseurl:"
  Jiny Study.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yk.poly.jiny.dev/" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  rain2473

source: src
destination: docs

layout:
  bgcolor: "#c8e6c9"
  width: "1200px"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
